* Development 14 | Recommended 1 *
* Since I have done so many things and fixed many bugs I thought I would
rush ahead to start Development 15 since I already have many new things
I wish to change and add

LIST OF CHANGES:

* Added TimerTest
* Added TouchEvent
* Added SystemInfo
* Added Debugging in Settings
* Added InputManagerAndroid
* Added FileUtilsTest
* Added GameMethodsInterface
* Added GameMethods
* Added EffectColour
* Added several methods into Colour
* Added a constructor in Colour to create a colour with the doubles: r g
b
* Added a constructor in Colour to create a colour with the integers: r
g b
* Added a constructor in Colour to create a colour with the integers: r
g b a
* Added the method onTouch() to components and input
* Added the method pause() in Timer
* Added the method resume() in Timer
* Added the method callOnTouch() in Input
* Added the method createDir() in FileUtils
* Added the method createDirs() in FileUtils
* Added the method copyDir() in FileUtils
* Added the method addAllFiles() in FileUtils
* Added the method listFiles() in FileUtils
* Added the method showYesNoOption() in MessageBox
* Added the method saveLogs() in Logger
* Added the method saveDebugLogs() in Logger
* Added the method saveInformationLogs() in Logger
* Added the method saveWarningLogs() in Logger
* Added the method saveErrorLogs() in Logger
* Added the method moveDir() in FileUtils
* Added the method isPlaying() in AudioClip
* Added the method isPlaying() in AndroidAudioClip
* Added the method isPlaying() in JavaAudioClip
* Added the method renderImage(Image image , double x , double y ,
double width , double height , double rotation) in BasicRendererJava
* Added the method renderImage(Image image , double x , double y ,
double width , double height , double rotation) in BasicRendererOpenGL
* Added the method renderImage(Image image , double x , double y ,
double width , double height , double rotation) in BasicRendererAndroid
* Added the method renderImage(Image image , double x , double y ,
double width , double height , double rotation) in BasicRenderer
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererJava
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererOpenGL
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererAndroid
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRenderer
* Added the method addGameMethodsInterface() in Game
* Added the variable EngineBuild in settings which holds the engines
build type e.g. Experimental, Beta
* Added sound to a GUIButton if wanted
* Added the variable rotation and rotationVelocity in Entity2D
* Added some get/set methods to Entity2D
* Added more debugging information
* Added the variable: showing in GUIPanel

* Created the package org.simplecorporation.myengine.core.game2d
* Created the package org.simplecorproation.myengine.core.game2d.entity
* Created the package
org.simplecorproation.myengine.core.game2d.entity.sprite
* Created the package org.simplecorporation.myengine.core.game2d.point

* Moved Entity2D to the package
org.simplecorporation.myengine.core.game2d.entity
* Moved AbstractEntity2D to the package
org.simplecorporation.myengine.core.game2d.entity
* Moved ImageEntity2D to the package
org.simplecorporation.myengine.core.game2d.entity
* Moved AnimatedEntity2D to the package
org.simplecorporation.myengine.core.game2d.entity
* Moved Sprite2D to the package
org.simplecorporation.myengine.core.game2d.entity.sprite
* Moved SpriteAnimation2D to the package
org.simplecorporation.myengine.core.game2d.entity.sprite
* Moved SpriteAnimation2DBuilder to the package
org.simplecorporation.myengine.core.game2d.entity.sprite
* Moved Point2D to org.simplecorporation.myengine.core.game2d.point

* Merged JavaGUIButton and AndroidGUIButton
* Merged JavaGUICheckBox and AndroidGUICheckBox
* Merged JavaGUITextDisplayArea and AndroidGUITextDisplayArea
* Merged JavaGUITextBox and AndroidGUITextBox

* Removed the package org.simplecorporation.myengine.core.game.entity
* Removed the package
org.simplecorporation.myengine.core.game.entity.sprite
* Removed the package org.simplecorporation.myengine.core.point

* Fixed problem with GUIRenderableButton: the android order of colours
was different to the one on pc
* Fixed problem with GUIImageButton: the android order of images was
different to the one on pc
* Fixed spelling mistake in Timer getTimePassed()
* Fixed bug: Settings readConfig() gave a NumberFormatException
* Fixed bug: PropertiesFile getProperty() didn't work properly
* Fixed bug: GUIFont not showing in a GUITextBox. This is a temporary
fix because it has taken away the feature of the default text having a
different alpha value. Please look at the issues section for more
information
* Fixed bug: Window size issue
* Fixed bug: Strange font issues drawing at y = 0
* Fixed bug: Bitmap font had wrong x, y, width and height. All problems
with Bitmap fonts should be fixed now :)
* Fixed bug: NoClassDefFoundError caused by updating a GUIButton
* Fixed bug: NoClassDefFoundError caused by updating a GUICheckBox
* Fixed bug: AndroidGUIFont was rendering in the wrong place
* Fixed bug: Settings readConfig() was not setting some of the settings
* Fixed bug: BitmapFont getWidth() = NaN when being used for the first
time

* Timer when stopped now gives the time it was running for rather than 0
in getTimePassed() and hasTimePassed()
* Image now outputs errors when loading error using the Logger as well
as calling e.printStackTrace()
* Tried to improve accuracy of BitmapFont's and TextBox's
* Settings now actually writes the configuration when writeConfig() is
called
* Changed some things to allow for continuous pressing of keys in a
GUITextBox (Holding down a letter/backspace now works)
* GUITextBox now makes text slide accross instead of limiting the text
input
* When Debugging is set to true some debug information is drawn on the
screen
* You no longer need to directly call methods in other classes to use
game methods such as gameUpdate(), you can use GameMethods and
GameMethodsInterface to get them instead
* ImageEntities now use the rotation values along with GUIComponents

* Note: Development will slow down a bit because of school work