* Development 14 | Development 7 *
* Added the method renderImage(Image image , double x , double y ,
double width , double height , double rotation) in BasicRenderer
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererJava
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererOpenGL
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRendererAndroid
* Added the method renderImage(Image image , double x , double y ,
double rotation) in BasicRenderer

* Fixed bug: NoClassDefFoundError caused by updating a GUIButton
* Fixed bug: NoClassDefFoundError caused by updating a GUICheckBox
* Fixed bug: GUIImageCheckBox didn't use the new rotation variable
* Fixed bug: AndroidGUIFont was rendering in the wrong place
* Fixed bug: AndroidBasicRenderer didn't rotate images properly